/*
 * Created on 2018-06-07 ( Date ISO 2018-06-07 - Time 14:43:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.util.Date;
import java.util.List;

import org.demo.data.record.MemberHumorRecord;

/**
 * Persistence Interface for MemberHumorRecord.
 */
public interface MemberHumorPersistence {

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * 
	 * @param memberId
	 * @param day
	 * @return entity
	 */
	MemberHumorRecord findById(Integer memberId, Date day);

	/**
	 * Finds all entities.
	 * 
	 * @return all entities
	 */
	List<MemberHumorRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * 
	 * @return
	 */
	public long countAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * 
	 * @param entity
	 * @return entity
	 */
	MemberHumorRecord save(MemberHumorRecord entity);

	/**
	 * Updates the given entity in the database
	 * 
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not
	 *         updated
	 */
	boolean update(MemberHumorRecord entity);

	/**
	 * Creates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	MemberHumorRecord create(MemberHumorRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * 
	 * @param memberId
	 * @param day
	 * @return true if the entity has been deleted, false if not found and not
	 *         deleted
	 */
	boolean deleteById(Integer memberId, Date day);

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * 
	 * @param the
	 *            entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not
	 *         deleted
	 */
	boolean delete(MemberHumorRecord entity);

	/**
	 * Returns true if an entity exists with the given Id / Primary Key
	 * 
	 * @param memberId
	 * @param day
	 * @return
	 */
	public boolean exists(Integer memberId, Date day);

	/**
	 * Returns true if the given entity exists
	 * 
	 * @param entity
	 * @return
	 */
	public boolean exists(MemberHumorRecord entity);

}
