/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import org.demo.data.record.TeamHumor;

/**
 * Persistence Interface for MemberHumorRecord.
 */
public interface TeamHumorPersistence {

	/**
	 * Calculate average team humor value for a specific day
	 * 
	 * @param string
	 * @return int representing arithmetical value of team humor level
	 */
	public TeamHumor calculateTeamHumor(String day);

	/**
	 * Give team humor for a specific day in JSON list of the different humor values
	 * from Humor enumeration int
	 * 
	 * @param ArrayList
	 *            int
	 * @return String
	 */

	public String giveTeamHumorText(Integer averageTeamHumor);

}
