/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean MemberRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class MemberRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class MemberRecord getters and setters ..." );
		
		MemberRecord memberRecord = new MemberRecord();


		//--- Test setter/getter for attribute "id"  ( model type : Integer / wrapperType : Integer )
		memberRecord.setId( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), memberRecord.getId() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "firstname"  ( model type : String / wrapperType : String )
		memberRecord.setFirstname( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", memberRecord.getFirstname() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "lastname"  ( model type : String / wrapperType : String )
		memberRecord.setLastname( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", memberRecord.getLastname() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "password"  ( model type : String / wrapperType : String )
		memberRecord.setPassword( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", memberRecord.getPassword() ) ; // Not primitive type in model


	}

}
