/*
 * Created on 2018-06-07 ( Date ISO 2018-06-07 - Time 15:31:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean MemberHumorRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class MemberHumorRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class MemberHumorRecord getters and setters ..." );
		
		MemberHumorRecord memberHumorRecord = new MemberHumorRecord();


		//--- Test setter/getter for attribute "memberId"  ( model type : Integer / wrapperType : Integer )
		memberHumorRecord.setMemberId( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), memberHumorRecord.getMemberId() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "day"  ( model type : Date / wrapperType : Date )
		memberHumorRecord.setDay( java.sql.Date.valueOf("2001-06-22") ) ;
		Assert.assertEquals( java.sql.Date.valueOf("2001-06-22"), memberHumorRecord.getDay() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "memberHumorLevel"  ( model type : Integer / wrapperType : Integer )
		memberHumorRecord.setMemberHumorLevel( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), memberHumorRecord.getMemberHumorLevel() ) ; // Not primitive type in model


	}

}
