/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean UserRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class UserRecord getters and setters ..." );
		
		UserRecord userRecord = new UserRecord();


		//--- Test setter/getter for attribute "id"  ( model type : Integer / wrapperType : Integer )
		userRecord.setId( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), userRecord.getId() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "firstName"  ( model type : String / wrapperType : String )
		userRecord.setFirstName( "A" ) ;
		Assert.assertEquals( "A", userRecord.getFirstName() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "lastName"  ( model type : String / wrapperType : String )
		userRecord.setLastName( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", userRecord.getLastName() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "password"  ( model type : String / wrapperType : String )
		userRecord.setPassword( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", userRecord.getPassword() ) ; // Not primitive type in model


	}

}
