/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean UserhumorRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserhumorRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class UserhumorRecord getters and setters ..." );
		
		UserhumorRecord userhumorRecord = new UserhumorRecord();


		//--- Test setter/getter for attribute "id"  ( model type : Integer / wrapperType : Integer )
		userhumorRecord.setId( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), userhumorRecord.getId() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "userId"  ( model type : Integer / wrapperType : Integer )
		userhumorRecord.setUserId( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), userhumorRecord.getUserId() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "day"  ( model type : Date / wrapperType : Date )
		userhumorRecord.setDay( java.sql.Date.valueOf("2001-06-22") ) ;
		Assert.assertEquals( java.sql.Date.valueOf("2001-06-22"), userhumorRecord.getDay() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "userHumorLevel"  ( model type : String / wrapperType : String )
		userhumorRecord.setUserHumorLevel( "AAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		Assert.assertEquals( "AAAAAAAAAAAAAAAAAAAAAAAAA", userhumorRecord.getUserHumorLevel() ) ; // Not primitive type in model


	}

}
