/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.demo.data.record.MemberHumorRecord ;
import org.demo.persistence.MemberHumorPersistence;

/**
 * Generic test class for a persistence service
 * 
 * @author Telosys 
 *
 */
public class MemberHumorPersistenceGenericTest {

	/**
	 * Generic test for a persistence service
	 * @param persistenceService
	 * @throws SQLException
	 */
	public void testPersistenceService(MemberHumorPersistence persistenceService) {
    	System.out.println("--- test MemberHumorPersistence ");

    	MemberHumorRecord memberHumor = new MemberHumorRecord();
		//--- Key values
		memberHumor.setId(Integer.valueOf(100)); // "ID" : java.lang.Integer
		//--- Other values
		memberHumor.setMemberId(Integer.valueOf(100)); // "MEMBER_ID" : java.lang.Integer
		memberHumor.setDay(java.sql.Date.valueOf("2001-06-22")); // "DAY" : java.util.Date
		memberHumor.setMemberHumorLevel("AAAAAAAAAAAAAAAAAAAAAAAAA"); // "MEMBER_HUMOR_LEVEL" : java.lang.String


    	//--- DELETE
    	System.out.println("Delete : " + memberHumor );
    	persistenceService.delete(memberHumor) ; // Just to be sure it doesn't exist before insert

		long initialCount = persistenceService.countAll() ;
    	System.out.println("Initial count = " + initialCount );

    	//--- CREATE
    	System.out.println("Create : " + memberHumor );

    	persistenceService.create(memberHumor);

    	assertTrue( persistenceService.exists(Integer.valueOf(100)) );

		assertTrue( persistenceService.exists(memberHumor) );
		long count = persistenceService.countAll() ;
    	System.out.println("Count = " + count );
		assertEquals(initialCount+1, count );

    	//--- FIND
    	System.out.println("Find by id..." );

    	MemberHumorRecord memberHumor2 = persistenceService.findById(Integer.valueOf(100));

    	System.out.println("Found : " + memberHumor2 );
    	assertNotNull(memberHumor2);
		assertTrue( memberHumor2.getId().equals(Integer.valueOf(100)) ) ;
    	assertTrue( persistenceService.exists(memberHumor2) ) ;
    	
    	//--- UPDATE
		//--- Change values
		memberHumor2.setMemberId(Integer.valueOf(200)); // "MEMBER_ID" : java.lang.Integer
		memberHumor2.setDay(java.sql.Date.valueOf("2002-06-22")); // "DAY" : java.util.Date
		memberHumor2.setMemberHumorLevel("BBBBBBBBBBBBBBBBBBBBBBBBB"); // "MEMBER_HUMOR_LEVEL" : java.lang.String
    	System.out.println("Update : " + memberHumor2 );
    	assertTrue( persistenceService.update(memberHumor2) );
    	
    	//--- RELOAD AFTER UPDATE
    	System.out.println("Find by id..." );

    	MemberHumorRecord memberHumor3 = persistenceService.findById(Integer.valueOf(100));
    	assertNotNull(memberHumor3);
    	System.out.println("Found : " + memberHumor3 );

		// Check same data in the reloaded instance
		assertEquals(memberHumor2.getMemberId(), memberHumor3.getMemberId() ); 
		assertEquals(memberHumor2.getDay(), memberHumor3.getDay() ); 
		assertEquals(memberHumor2.getMemberHumorLevel(), memberHumor3.getMemberHumorLevel() ); 

    	//--- DELETE
    	System.out.println("Delete : " + memberHumor2 );
    	assertTrue( persistenceService.delete(memberHumor2) ); // Delete #1 : OK
    	assertFalse( persistenceService.delete(memberHumor2) ); // Nothing (already deleted)
    	assertFalse( persistenceService.deleteById(Integer.valueOf(100)) ); // Nothing (already deleted)

		long finalCount = persistenceService.countAll() ;
    	System.out.println("Final count = " + finalCount );
		assertEquals(initialCount, finalCount);

    	assertFalse( persistenceService.exists(Integer.valueOf(100)) ) ;
    	assertFalse( persistenceService.exists(memberHumor2) ) ;
    	memberHumor2 = persistenceService.findById(Integer.valueOf(100));
    	assertNull( memberHumor2 );
    	
    	System.out.println("Normal end of persistence service test." );
	}
}
