/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.demo.data.record.UserRecord ;
import org.demo.persistence.UserPersistence;

/**
 * Generic test class for a persistence service
 * 
 * @author Telosys 
 *
 */
public class UserPersistenceGenericTest {

	/**
	 * Generic test for a persistence service
	 * @param persistenceService
	 * @throws SQLException
	 */
	public void testPersistenceService(UserPersistence persistenceService) {
    	System.out.println("--- test UserPersistence ");

    	UserRecord user = new UserRecord();
		//--- Key values
		user.setId(Integer.valueOf(100)); // "ID" : java.lang.Integer
		//--- Other values
		user.setFirstName("A"); // "FIRSTNAME" : java.lang.String
		user.setLastName("AAAAAAAAAAAAAAAAAAAAAAAAA"); // "LASTNAME" : java.lang.String
		user.setPassword("AAAAAAAAAAAAAAAAAAAAAAAAA"); // "PASSWORD" : java.lang.String


    	//--- DELETE
    	System.out.println("Delete : " + user );
    	persistenceService.delete(user) ; // Just to be sure it doesn't exist before insert

		long initialCount = persistenceService.countAll() ;
    	System.out.println("Initial count = " + initialCount );

    	//--- CREATE
    	System.out.println("Create : " + user );

    	persistenceService.create(user);

    	assertTrue( persistenceService.exists(Integer.valueOf(100)) );

		assertTrue( persistenceService.exists(user) );
		long count = persistenceService.countAll() ;
    	System.out.println("Count = " + count );
		assertEquals(initialCount+1, count );

    	//--- FIND
    	System.out.println("Find by id..." );

    	UserRecord user2 = persistenceService.findById(Integer.valueOf(100));

    	System.out.println("Found : " + user2 );
    	assertNotNull(user2);
		assertTrue( user2.getId().equals(Integer.valueOf(100)) ) ;
    	assertTrue( persistenceService.exists(user2) ) ;
    	
    	//--- UPDATE
		//--- Change values
		user2.setFirstName("B"); // "FIRSTNAME" : java.lang.String
		user2.setLastName("BBBBBBBBBBBBBBBBBBBBBBBBB"); // "LASTNAME" : java.lang.String
		user2.setPassword("BBBBBBBBBBBBBBBBBBBBBBBBB"); // "PASSWORD" : java.lang.String
    	System.out.println("Update : " + user2 );
    	assertTrue( persistenceService.update(user2) );
    	
    	//--- RELOAD AFTER UPDATE
    	System.out.println("Find by id..." );

    	UserRecord user3 = persistenceService.findById(Integer.valueOf(100));
    	assertNotNull(user3);
    	System.out.println("Found : " + user3 );

		// Check same data in the reloaded instance
		assertEquals(user2.getFirstName(), user3.getFirstName() ); 
		assertEquals(user2.getLastName(), user3.getLastName() ); 
		assertEquals(user2.getPassword(), user3.getPassword() ); 

    	//--- DELETE
    	System.out.println("Delete : " + user2 );
    	assertTrue( persistenceService.delete(user2) ); // Delete #1 : OK
    	assertFalse( persistenceService.delete(user2) ); // Nothing (already deleted)
    	assertFalse( persistenceService.deleteById(Integer.valueOf(100)) ); // Nothing (already deleted)

		long finalCount = persistenceService.countAll() ;
    	System.out.println("Final count = " + finalCount );
		assertEquals(initialCount, finalCount);

    	assertFalse( persistenceService.exists(Integer.valueOf(100)) ) ;
    	assertFalse( persistenceService.exists(user2) ) ;
    	user2 = persistenceService.findById(Integer.valueOf(100));
    	assertNull( user2 );
    	
    	System.out.println("Normal end of persistence service test." );
	}
}
