/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.demo.data.record.UserhumorRecord ;
import org.demo.persistence.UserhumorPersistence;

/**
 * Generic test class for a persistence service
 * 
 * @author Telosys 
 *
 */
public class UserhumorPersistenceGenericTest {

	/**
	 * Generic test for a persistence service
	 * @param persistenceService
	 * @throws SQLException
	 */
	public void testPersistenceService(UserhumorPersistence persistenceService) {
    	System.out.println("--- test UserhumorPersistence ");

    	UserhumorRecord userhumor = new UserhumorRecord();
		//--- Key values
		userhumor.setId(Integer.valueOf(100)); // "ID" : java.lang.Integer
		//--- Other values
		userhumor.setUserId(Integer.valueOf(100)); // "USER_ID" : java.lang.Integer
		userhumor.setDay(java.sql.Date.valueOf("2001-06-22")); // "DAY" : java.util.Date
		userhumor.setUserHumorLevel("AAAAAAAAAAAAAAAAAAAAAAAAA"); // "USERHUMORLEVEL" : java.lang.String


    	//--- DELETE
    	System.out.println("Delete : " + userhumor );
    	persistenceService.delete(userhumor) ; // Just to be sure it doesn't exist before insert

		long initialCount = persistenceService.countAll() ;
    	System.out.println("Initial count = " + initialCount );

    	//--- CREATE
    	System.out.println("Create : " + userhumor );

    	persistenceService.create(userhumor);

    	assertTrue( persistenceService.exists(Integer.valueOf(100)) );

		assertTrue( persistenceService.exists(userhumor) );
		long count = persistenceService.countAll() ;
    	System.out.println("Count = " + count );
		assertEquals(initialCount+1, count );

    	//--- FIND
    	System.out.println("Find by id..." );

    	UserhumorRecord userhumor2 = persistenceService.findById(Integer.valueOf(100));

    	System.out.println("Found : " + userhumor2 );
    	assertNotNull(userhumor2);
		assertTrue( userhumor2.getId().equals(Integer.valueOf(100)) ) ;
    	assertTrue( persistenceService.exists(userhumor2) ) ;
    	
    	//--- UPDATE
		//--- Change values
		userhumor2.setUserId(Integer.valueOf(200)); // "USER_ID" : java.lang.Integer
		userhumor2.setDay(java.sql.Date.valueOf("2002-06-22")); // "DAY" : java.util.Date
		userhumor2.setUserHumorLevel("BBBBBBBBBBBBBBBBBBBBBBBBB"); // "USERHUMORLEVEL" : java.lang.String
    	System.out.println("Update : " + userhumor2 );
    	assertTrue( persistenceService.update(userhumor2) );
    	
    	//--- RELOAD AFTER UPDATE
    	System.out.println("Find by id..." );

    	UserhumorRecord userhumor3 = persistenceService.findById(Integer.valueOf(100));
    	assertNotNull(userhumor3);
    	System.out.println("Found : " + userhumor3 );

		// Check same data in the reloaded instance
		assertEquals(userhumor2.getUserId(), userhumor3.getUserId() ); 
		assertEquals(userhumor2.getDay(), userhumor3.getDay() ); 
		assertEquals(userhumor2.getUserHumorLevel(), userhumor3.getUserHumorLevel() ); 

    	//--- DELETE
    	System.out.println("Delete : " + userhumor2 );
    	assertTrue( persistenceService.delete(userhumor2) ); // Delete #1 : OK
    	assertFalse( persistenceService.delete(userhumor2) ); // Nothing (already deleted)
    	assertFalse( persistenceService.deleteById(Integer.valueOf(100)) ); // Nothing (already deleted)

		long finalCount = persistenceService.countAll() ;
    	System.out.println("Final count = " + finalCount );
		assertEquals(initialCount, finalCount);

    	assertFalse( persistenceService.exists(Integer.valueOf(100)) ) ;
    	assertFalse( persistenceService.exists(userhumor2) ) ;
    	userhumor2 = persistenceService.findById(Integer.valueOf(100));
    	assertNull( userhumor2 );
    	
    	System.out.println("Normal end of persistence service test." );
	}
}
