/*
   H2 test database schema creation 
 */

/* Create table for entity Member */
CREATE TABLE MEMBER (
ID INTEGER NOT NULL,
FIRSTNAME VARCHAR NOT NULL,
LASTNAME VARCHAR NOT NULL,
PASSWORD VARCHAR NOT NULL,
PRIMARY KEY(ID)
);

/* Create table for entity MemberHumor */
CREATE TABLE MEMBER_HUMOR (
ID INTEGER NOT NULL,
MEMBER_ID INTEGER NOT NULL,
DAY DATE NOT NULL,
MEMBER_HUMOR_LEVEL VARCHAR NOT NULL,
PRIMARY KEY(ID)
);

