/*
   H2 test database schema creation 
 */

/* Create table for entity User */
CREATE TABLE USER (
ID INTEGER NOT NULL,
FIRSTNAME VARCHAR ,
LASTNAME VARCHAR NOT NULL,
PASSWORD VARCHAR NOT NULL,
PRIMARY KEY(ID)
);

/* Create table for entity Userhumor */
CREATE TABLE USERHUMOR (
ID INTEGER NOT NULL,
USER_ID INTEGER NOT NULL,
DAY DATE NOT NULL,
USERHUMORLEVEL VARCHAR NOT NULL,
PRIMARY KEY(ID)
);

