/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.MemberRecord;
import org.demo.persistence.MemberPersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Member persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("MemberPersistence")
public class MemberPersistenceFake extends GenericFakeDAO<MemberRecord> implements MemberPersistence {

	/**
	 * Constructor
	 */
	public MemberPersistenceFake() {
		super(MemberRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private MemberRecord newInstanceWithPrimaryKey(Integer id) {
		MemberRecord record = new MemberRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(MemberRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(MemberRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public MemberRecord create(MemberRecord record) {
		super.doCreate(record);
		return record;
	}

	@Override
	public boolean delete(MemberRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		MemberRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(MemberRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		MemberRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<MemberRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public MemberRecord findById(Integer id) {
        MemberRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public MemberRecord save(MemberRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreate(record);
		}
        return record;
	}

	@Override
	public boolean update(MemberRecord record) {
		return super.doUpdate(record);	
	}
}
