/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.MemberHumorRecord;
import org.demo.persistence.MemberHumorPersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * MemberHumor persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("MemberHumorPersistence")
public class MemberHumorPersistenceFake extends GenericFakeDAO<MemberHumorRecord> implements MemberHumorPersistence {

	/**
	 * Constructor
	 */
	public MemberHumorPersistenceFake() {
		super(MemberHumorRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private MemberHumorRecord newInstanceWithPrimaryKey(Integer id) {
		MemberHumorRecord record = new MemberHumorRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(MemberHumorRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(MemberHumorRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public MemberHumorRecord create(MemberHumorRecord record) {
		super.doCreate(record);
		return record;
	}

	@Override
	public boolean delete(MemberHumorRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		MemberHumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(MemberHumorRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		MemberHumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<MemberHumorRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public MemberHumorRecord findById(Integer id) {
        MemberHumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public MemberHumorRecord save(MemberHumorRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreate(record);
		}
        return record;
	}

	@Override
	public boolean update(MemberHumorRecord record) {
		return super.doUpdate(record);	
	}
}
