/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.UserhumorRecord;
import org.demo.persistence.UserhumorPersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Userhumor persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("UserhumorPersistence")
public class UserhumorPersistenceFake extends GenericFakeDAO<UserhumorRecord> implements UserhumorPersistence {

	/**
	 * Constructor
	 */
	public UserhumorPersistenceFake() {
		super(UserhumorRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private UserhumorRecord newInstanceWithPrimaryKey(Integer id) {
		UserhumorRecord record = new UserhumorRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(UserhumorRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(UserhumorRecord record, long value) {
		throw new IllegalStateException("Unexpected call to method 'setAutoIncrementedKey'");
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public UserhumorRecord create(UserhumorRecord record) {
		super.doCreate(record);
		return record;
	}

	@Override
	public boolean delete(UserhumorRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		UserhumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(UserhumorRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		UserhumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<UserhumorRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public UserhumorRecord findById(Integer id) {
        UserhumorRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public UserhumorRecord save(UserhumorRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreate(record);
		}
        return record;
	}

	@Override
	public boolean update(UserhumorRecord record) {
		return super.doUpdate(record);	
	}
}
