/*
 * Created on 2018-06-07 ( Date ISO 2018-06-07 - Time 15:31:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;



import org.demo.persistence.MemberHumorPersistence ;
import org.demo.persistence.impl.jdbc.commons.DAOTestUtil;
import org.demo.persistence.MemberHumorPersistenceGenericTest;

import org.junit.BeforeClass;
import org.junit.Test;


/**
 * JUnit tests for MemberHumorDAO
 * 
 * @author Telosys Tools
 *
 */
public class MemberHumorPersistenceJdbcTest extends MemberHumorPersistenceGenericTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE MEMBER_HUMOR ("
			+ "MEMBER_ID INTEGER NOT NULL,"
			+ "DAY DATE NOT NULL,"
			+ "MEMBER_HUMOR_LEVEL INTEGER NOT NULL,"
			+ "PRIMARY KEY(MEMBER_ID,DAY)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE, "MEMBER_HUMOR") ;
	}

	@Test
	public void testPersistenceService() {

    	MemberHumorPersistence persistenceService = new MemberHumorPersistenceJdbc();

    	testPersistenceService(persistenceService);
	}	

}
