/*
 * Created on 2018-04-20 ( Date ISO 2018-04-20 - Time 11:46:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;



import org.demo.persistence.UserPersistence ;
import org.demo.persistence.impl.jdbc.commons.DAOTestUtil;
import org.demo.persistence.UserPersistenceGenericTest;

import org.junit.BeforeClass;
import org.junit.Test;


/**
 * JUnit tests for UserDAO
 * 
 * @author Telosys Tools
 *
 */
public class UserPersistenceJdbcTest extends UserPersistenceGenericTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE USER ("
			+ "ID INTEGER NOT NULL,"
			+ "FIRSTNAME VARCHAR ,"
			+ "LASTNAME VARCHAR NOT NULL,"
			+ "PASSWORD VARCHAR NOT NULL,"
			+ "PRIMARY KEY(ID)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE, "USER") ;
	}

	@Test
	public void testPersistenceService() {

    	UserPersistence persistenceService = new UserPersistenceJdbc();

    	testPersistenceService(persistenceService);
	}	

}
