/*
 * Created on 2018-04-20 ( Date ISO 2018-04-20 - Time 11:46:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;



import org.demo.persistence.UserhumorPersistence ;
import org.demo.persistence.impl.jdbc.commons.DAOTestUtil;
import org.demo.persistence.UserhumorPersistenceGenericTest;

import org.junit.BeforeClass;
import org.junit.Test;


/**
 * JUnit tests for UserhumorDAO
 * 
 * @author Telosys Tools
 *
 */
public class UserhumorPersistenceJdbcTest extends UserhumorPersistenceGenericTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE USERHUMOR ("
			+ "ID INTEGER NOT NULL,"
			+ "USER_ID INTEGER NOT NULL,"
			+ "DAY DATE NOT NULL,"
			+ "USERHUMORLEVEL VARCHAR NOT NULL,"
			+ "PRIMARY KEY(ID)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE, "USERHUMOR") ;
	}

	@Test
	public void testPersistenceService() {

    	UserhumorPersistence persistenceService = new UserhumorPersistenceJdbc();

    	testPersistenceService(persistenceService);
	}	

}
