/*
 * Created on 2018-04-23 ( Time 14:28:05 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.time.LocalDate;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import org.demo.data.record.TeamHumor;
import org.demo.persistence.TeamHumorPersistence;
// import org.demo.business.service.impl.MemberHumorServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;

/**
 * JAXRS Jersey controller for 'MemberHumor' management.
 */
@Path("/teamHumor")
public class TeamHumorResource extends AbstractResourceController {

	private TeamHumorPersistence teamHumorService = PersistenceServiceProvider.getService(TeamHumorPersistence.class);

	/**
	 * Constructor
	 */
	public TeamHumorResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Calculate and retrieves average humor of team for the current day
	 *
	 * @param date
	 * @return 200 + body if found, 404 if not found
	 */
	@GET
	@Produces({ MediaType.APPLICATION_JSON })
	public Response getTeamHumorByDay() {
		LocalDate today = LocalDate.now();
		String todayString = today.toString();
		logger.info("Default getHumorByDay(" + today + ")...");

		TeamHumor teamHumor = teamHumorService.calculateTeamHumor(todayString);
		if (teamHumor != null) {
			return Response.ok(teamHumor).build();
		} else {
			return Response.status(Status.BAD_REQUEST).build();
		}
	}

	/**
	 * Calculate and retrieves average humor of team for a specific day.
	 *
	 * @param date
	 * @return 200 + body if found, 404 if not found
	 */
	@GET
	@Path("/{day}")
	@Produces({ MediaType.APPLICATION_JSON })
	public Response getTeamHumorByDay(@PathParam("day") String day) {
		logger.info("getHumorByDay(" + day + ")...");
		TeamHumor teamHumor = teamHumorService.calculateTeamHumor(day);
		return Response.ok(teamHumor).build();
	}
}
