/*
 * Created on 2018-04-16 ( Time 11:56:15 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.UserhumorRecord;
import org.demo.data.record.listitem.UserhumorListItem;


//--- Services 
import org.demo.persistence.UserhumorPersistence;
// import org.demo.business.service.impl.UserhumorServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'Userhumor' management.
 */
@Path("/userhumor")
public class UserhumorResource extends AbstractResourceController {

	private UserhumorPersistence userhumorService = PersistenceServiceProvider.getService(UserhumorPersistence.class);

	/**
	 * Constructor
	 */
	public UserhumorResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all userhumor entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<UserhumorRecord> findAll() {
		logger.info("findAll()...");
		return userhumorService.findAll();
	}

	/**
	 * Retrieves a userhumor using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") Integer id) {
		logger.info("findById("+id+")...");
		UserhumorRecord record = userhumorService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new userhumor.
	 * @param userhumor userhumor
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(UserhumorRecord userhumor) {
		logger.info("create()...");
		if ( userhumorService.exists(userhumor) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			UserhumorRecord record = userhumorService.create(userhumor);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the userhumor identified by the given id
	 * @param userhumor userhumor entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public UserhumorRecord update(UserhumorRecord userhumor, @PathParam("id") Integer id) {
	public Response update(UserhumorRecord userhumor, @PathParam("id") Integer id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		userhumor.setId( id );
		boolean updated = userhumorService.update(userhumor);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given userhumor.
	 * @param userhumor userhumor entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(UserhumorRecord userhumor) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! userhumorService.exists(userhumor) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		UserhumorRecord record = userhumorService.save(userhumor);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a userhumor.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") Integer id) {
	public Response delete(@PathParam("id") Integer id) {
		logger.info("delete("+id+")...");
		// userhumorService.deleteById(id);
		boolean deleted = userhumorService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/userhumors-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<UserhumorListItem> listItems() {
		logger.info("listItems()...");
		List<UserhumorRecord> list = userhumorService.findAll();
		List<UserhumorListItem> items = new LinkedList<UserhumorListItem>();
		for ( UserhumorRecord userhumor : list ) {
			items.add(new UserhumorListItem( userhumor ) );
		}
		return items;
	}

}
