/*
 * Created on 2018-04-16 ( Time 11:56:15 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.web.rest.jaxrs;

import java.util.LinkedList;
import java.util.List;

//--- Entities
import org.demo.data.record.UserRecord;
import org.demo.data.record.listitem.UserListItem;


//--- Services 
import org.demo.persistence.UserPersistence;
// import org.demo.business.service.impl.UserServiceImpl;
import org.demo.persistence.commons.PersistenceServiceProvider;
import org.demo.web.rest.commons.AbstractResourceController;



import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

/**
 * JAXRS Jersey controller for 'User' management.
 */
@Path("/user")
public class UserResource extends AbstractResourceController {

	private UserPersistence userService = PersistenceServiceProvider.getService(UserPersistence.class);

	/**
	 * Constructor
	 */
	public UserResource() {
		super();
		logger.info("Constructor.");
	}

	/**
	 * Get all user entities.
	 * @return list with all entities found
	 */
	@GET
	@Produces({MediaType.APPLICATION_JSON})
	public List<UserRecord> findAll() {
		logger.info("findAll()...");
		return userService.findAll();
	}

	/**
	 * Retrieves a user using the given id.
	 * @param id id
	 * @return 200 + body if found, 404 if not found 
	 */
	@GET
	@Path("{id}")
	@Produces({MediaType.APPLICATION_JSON})
	public Response findById(@PathParam("id") Integer id) {
		logger.info("findById("+id+")...");
		UserRecord record = userService.findById(id);
		if ( record != null ) {
			return Response.ok(record).build();
		}
		else {
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Creates a new user.
	 * @param user user
	 * @return 201 with body if created, 409 conflict if duplicate key 
	 */	
	@POST
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response create(UserRecord user) {
		logger.info("create()...");
		if ( userService.exists(user) ) {
			logger.info("create() : already exists -> conflict");
			return Response.status(Status.CONFLICT).build();
		}
		else {
			logger.info("create() : doesn't exist -> create");
			UserRecord record = userService.create(user);
			return Response.status(Status.CREATED).entity(record).build();
		}
	}

//------------------------------------------------------------
	/**
	 * Updates the user identified by the given id
	 * @param user user entity
	 * @param id id 
	 * @return 200 if found and updated, 404 if not found 
	 */	
	@PUT
	@Path("{id}")
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	// public UserRecord update(UserRecord user, @PathParam("id") Integer id) {
	public Response update(UserRecord user, @PathParam("id") Integer id) {
		logger.info("update()...");
		// force the id (use the id provided by the URL)
		user.setId( id );
		boolean updated = userService.update(user);
		if ( updated ) {
			// Actually updated (found and updated) => 200 OK
			return Response.status(Status.OK).build();
		}
		else {
			// Not updated with no error => 404 not found
			return Response.status(Status.NOT_FOUND).build();
		}
	}

	/**
	 * Save (create or update) the given user.
	 * @param user user entity
	 * @return 200 if found and updated, 201 if not found and created
	 */	
	@PUT
	@Consumes({MediaType.APPLICATION_JSON})
	@Produces({MediaType.APPLICATION_JSON})
	public Response save(UserRecord user) {
		logger.info("save()...");
		Status status = Status.OK ; // 200 OK
		if ( ! userService.exists(user) ) {
			status = Status.CREATED ; // 201 CREATED
		}
		UserRecord record = userService.save(user);
		// Response ( code 200 or 201 )
		return Response.status(status).entity(record).build();
	}


//------------------------------------------------------------
	/**
	 * Delete a user.
	 * @param id id
	 */
	@DELETE
	@Path("{id}")
	//@Consumes({MediaType.APPLICATION_JSON})
	// public void delete(@PathParam("id") Integer id) {
	public Response delete(@PathParam("id") Integer id) {
		logger.info("delete("+id+")...");
		// userService.deleteById(id);
		boolean deleted = userService.deleteById(id);
		if ( deleted ) {
			// Actually deleted (found and deleted) => 204 "No Content" because no body in the response 
			return Response.status(Status.NO_CONTENT).build();
		}
		else {
			// Not deleted with no error => 404 "Not found"
			return Response.status(Status.NOT_FOUND).build();
		}
}

	@GET
	@Path("/users-list-items")
	@Produces({MediaType.APPLICATION_JSON})
	public List<UserListItem> listItems() {
		logger.info("listItems()...");
		List<UserRecord> list = userService.findAll();
		List<UserListItem> items = new LinkedList<UserListItem>();
		for ( UserRecord user : list ) {
			items.add(new UserListItem( user ) );
		}
		return items;
	}

}
