/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.MemberRecord;
import org.demo.commons.ListItem;

public class MemberListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public MemberListItem(MemberRecord member) {
		super();

		this.value = ""
			 + member.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = member.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
