/*
 * Created on 2018-04-30 ( Date ISO 2018-04-30 - Time 15:08:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.MemberHumorRecord;
import org.demo.commons.ListItem;

public class MemberHumorListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public MemberHumorListItem(MemberHumorRecord memberHumor) {
		super();

		this.value = ""
			 + memberHumor.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = memberHumor.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
