/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceServicePattern {

	// Set the persistence service class pattern below ...
	public final static String  PATTERN = PersistenceFakeServicePattern.PATTERN ;
	
	// public final static String  PATTERN = PersistenceJdbcServicePattern.PATTERN ;
	// public final static String  PATTERN = PersistenceJPAServicePattern.PATTERN ;
}
