/*
 * Created on 2018-04-20 ( Date ISO 2018-04-20 - Time 11:46:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceJdbcServicePattern {

	public final static String  PATTERN = "%s.impl.jdbc.%sJdbc" ;
	
}
