/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import org.demo.persistence.MemberPersistence ;
import org.demo.persistence.MemberPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Member persistence service
 * 
 * @author Telosys Tools
 *
 */
public class MemberPersistenceFakeTest extends MemberPersistenceGenericTest {

	@Test
	public void testPersistenceService() {
    	System.out.println("test MemberPersistenceFake ");

    	MemberPersistence persistenceService = new MemberPersistenceFake();

    	testPersistenceService(persistenceService);

	}	
}
