/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import org.demo.persistence.UserhumorPersistence ;
import org.demo.persistence.UserhumorPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Userhumor persistence service
 * 
 * @author Telosys Tools
 *
 */
public class UserhumorPersistenceFakeTest extends UserhumorPersistenceGenericTest {

	@Test
	public void testPersistenceService() {
    	System.out.println("test UserhumorPersistenceFake ");

    	UserhumorPersistence persistenceService = new UserhumorPersistenceFake();

    	testPersistenceService(persistenceService);

	}	
}
