/*
 * Created on 2018-04-16 ( Date ISO 2018-04-16 - Time 11:56:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import org.demo.persistence.UserPersistence ;
import org.demo.persistence.UserPersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for User persistence service
 * 
 * @author Telosys Tools
 *
 */
public class UserPersistenceFakeTest extends UserPersistenceGenericTest {

	@Test
	public void testPersistenceService() {
    	System.out.println("test UserPersistenceFake ");

    	UserPersistence persistenceService = new UserPersistenceFake();

    	testPersistenceService(persistenceService);

	}	
}
