/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "MEMBER" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class MemberRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer id ; // Integer // Id or Primary Key

    @NotNull
    @Size( min = 1, max = 25 )
    private String firstname ;  // String 
    @NotNull
    @Size( min = 1, max = 25 )
    private String lastname ;  // String 
    @NotNull
    @Size( min = 1, max = 25 )
    private String password ;  // String 

    /**
     * Default constructor
     */
    public MemberRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "ID" ( type "INTEGER", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "ID" ( type "INTEGER", NotNull : true ) 
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "firstname" field value
     * This field is mapped on the database column "FIRSTNAME" ( type "VARCHAR", NotNull : true ) 
     * @param firstname
     */
    public void setFirstname( String firstname ) {
        this.firstname = firstname;
    }
    /**
     * Get the "firstname" field value
     * This field is mapped on the database column "FIRSTNAME" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Set the "lastname" field value
     * This field is mapped on the database column "LASTNAME" ( type "VARCHAR", NotNull : true ) 
     * @param lastname
     */
    public void setLastname( String lastname ) {
        this.lastname = lastname;
    }
    /**
     * Get the "lastname" field value
     * This field is mapped on the database column "LASTNAME" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Set the "password" field value
     * This field is mapped on the database column "PASSWORD" ( type "VARCHAR", NotNull : true ) 
     * @param password
     */
    public void setPassword( String password ) {
        this.password = password;
    }
    /**
     * Get the "password" field value
     * This field is mapped on the database column "PASSWORD" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getPassword() {
        return this.password;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(firstname);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(password);
        return sb.toString(); 
    } 



}
