/*
 * Created on 2018-04-23 ( Date ISO 2018-04-23 - Time 14:26:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;

/**
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 *
 */
public class TeamHumor {

	private String day; // String

	private Integer ValuesNumber; // Integer

	private Integer teamHumorValue; // Integer

	private String teamHumorText; // String

	/**
	 * Default constructor
	 */
	public TeamHumor() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
	// ----------------------------------------------------------------------

	public String getDay() {
		return day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public Integer getValuesNumber() {
		return ValuesNumber;
	}

	public void setValuesNumber(Integer valuesNumber) {
		ValuesNumber = valuesNumber;
	}

	public int getTeamHumorValue() {
		return teamHumorValue;
	}

	public void setTeamHumorValue(int teamHumorValue) {
		this.teamHumorValue = teamHumorValue;
	}

	public String getTeamHumorText() {
		return teamHumorText;
	}

	public void setTeamHumorText(String teamHumor) {
		this.teamHumorText = teamHumor;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(day);
		sb.append("|");
		sb.append(teamHumorValue);
		sb.append("|");
		sb.append(teamHumorText);

		return sb.toString();
	}

}
